taxonomy_codes = {
'208D00000X': 'Allopathic &amp; Osteopathic Physicians/General Practice',
'208600000X': 'Allopathic &amp; Osteopathic Physicians/Surgery',
'2086H0002X': 'Allopathic &amp; Osteopathic Physicians/Surgery/Hospice and Palliative Medicine, General Surgery',
'2086S0120X': 'Allopathic &amp; Osteopathic Physicians/Surgery/Pediatric Surgery',
'2086S0122X': 'Allopathic &amp; Osteopathic Physicians/Surgery/Plastic and Reconstructive Surgery',
'2086S0105X': 'Allopathic &amp; Osteopathic Physicians/Surgery, Surgery of the Hand',
'2086S0102X': 'Allopathic &amp; Osteopathic Physicians/Surgery/Surgical Critical Care',
'2086X0206X': 'Allopathic &amp; Osteopathic Physicians/Surgery, Surgical Oncology',
'2086S0127X': 'Allopathic &amp; Osteopathic Physicians/Surgery/Trauma Surgery',
'2086S0129X': 'Allopathic &amp; Osteopathic Physicians/Surgery, Vascular Surgery',
'208G00000X': 'Allopathic &amp; Osteopathic Physicians/Thoracic Surgery (Cardiothoracic Vascular Surgery)',
'204F00000X': 'Allopathic &amp; Osteopathic Physicians/Transplant Surgery',
'208C00000X': 'Allopathic &amp; Osteopathic Physicians/Colon &amp; Rectal Surgery',
'207T00000X': 'Allopathic &amp; Osteopathic Physicians/Neurological Surgery',
'204E00000X': 'Allopathic &amp; Osteopathic Physicians/Oral and Maxillofacial Surgery',
'207X00000X': 'Allopathic &amp; Osteopathic Physicians/Orthopedic Surgery',
'207XS0114X': 'Allopathic &amp; Osteopathic Physicians/Orthopedic Surgery, Adult Reconstructive Orthopedic Surgery',
'207XX0004X': 'Allopathic &amp; Osteopathic Physicians/Orthopedic Surgery, Foot and Ankle Surgery',
'207XS0106X': 'Allopathic &amp; Osteopathic Physicians/Orthopedic Surgery, Hand Surgery',
'207XS0117X': 'Allopathic &amp; Osteopathic Physicians/Orthopedic Surgery, Orthopedic Surgery of the Spine',
'207XX0801X': 'Allopathic &amp; Osteopathic Physicians/Orthopedic Surgery, Orthopedic Trauma',
'207XP3100X': 'Allopathic &amp; Osteopathic Physicians/Orthopedic Surgery, Pediatric Orthopedic Surgery',
'207XX0005X': 'Allopathic &amp; Osteopathic Physicians/Orthopedic Surgery/Sports Medicine',
'208200000X': 'Allopathic &amp; Osteopathic Physicians/Plastic Surgery',
'2082S0099X': 'Allopathic &amp; Osteopathic Physicians/Plastic Surgery, Plastic Surgery Within the Head and Neck',
'2082S0105X': 'Allopathic &amp; Osteopathic Physicians/Plastic Surgery, Surgery of the Hand',
'207K00000X ': 'Allopathic &amp; Osteopathic Physicians/Allergy and Immunology',
'207KA0200X': 'Allopathic &amp; Osteopathic Physicians/Allergy and Immunology/Allergy',
'207KI0005X': 'Allopathic &amp; Osteopathic Physicians/Allergy and Immunology/Clinical &amp; Laboratory Immunology',
'207Y00000X ': 'Allopathic &amp; Osteopathic Physicians/ Otolaryngology ',
'207YS0123X': 'Allopathic &amp; Osteopathic Physicians/ Otolaryngology/Facial Plastic Surgery',
'207YX0602X': 'Allopathic &amp; Osteopathic Physicians/Otolaryngology/Otolaryngic Allergy',
'207YX0905X': 'Allopathic &amp; Osteopathic Physicians/Otolaryngology/Otolaryngology/Facial Plastic Surgery',
'207YX0901X': 'Allopathic &amp; Osteopathic Physicians/Otolaryngology/Otology &amp;Neurotology',
'207YP0228X': 'Allopathic &amp; Osteopathic Physicians/Otolaryngology/Pediatric Otolaryngology',
'207YX0007X': 'Allopathic &amp; Osteopathic Physicians/Otolaryngology/Plastic Surgery within the Head &amp; Neck',
'207YS0012X': 'Allopathic &amp; Osteopathic Physicians/Otolaryngology/Sleep Medicine',
'207L00000X ': 'Allopathic &amp; Osteopathic Physicians/Anesthesiology',
'207LA0401X': 'Allopathic &amp; Osteopathic Physicians/Anesthesiology/Addiction Medicine',
'207LC0200X': 'Allopathic &amp; Osteopathic Physicians/Anesthesiology/Critical Care Medicine',
'207LH0002X': 'Allopathic &amp; Osteopathic Physicians/Surgery/Hospice and Palliative Medicine, Anesthesiology',
'207LP2900X': 'Allopathic &amp; Osteopathic Physicians/Anesthesiology/Pain Medicine',
'207LP3000X': 'Allopathic &amp; Osteopathic Physicians/Anesthesiology/Pediatric Anesthesiology',
'207RC0000X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Cardiovascular Disease',
'207N00000X ': 'Allopathic &amp; Osteopathic Physicians/Dermatology',
'207NI0002X': 'Allopathic &amp; Osteopathic Physicians/Dermatology, Clinical &amp; Laboratory Dermatological Immunology',
'207ND0101X': 'Allopathic &amp; Osteopathic Physicians/Dermatology, MOHS-Micrographic Surgery',
'207ND0900X': 'Allopathic &amp; Osteopathic Physicians/Dermatology, Dermapathology',
'207NP0225X': 'Allopathic &amp; Osteopathic Physicians/Dermatology, Pediatric Dermatology',
'207NS0135X': 'Allopathic &amp;Osteopathic Physicians/Dermatology, Procedural Dermatology',
'207Q00000X ': 'Allopathic &amp; Osteopathic Physicians/Family Medicine',
'207QA0401X': 'Allopathic &amp; Osteopathic Physicians/Family Medicine, Addiction Medicine',
'207QA0000X': 'Allopathic &amp; Osteopathic Physicians/Family Medicine, Adolescent Medicine',
'207QA0505X': 'Allopathic &amp; Osteopathic Physicians/Family Medicine, Adult Medicine',
'207QB0002X': 'Allopathic &amp; Osteopathic Physicians/Family Medicine, Bariatric Medicine',
'207QG0300X': 'Allopathic &amp; Osteopathic Physicians/Family Medicine, Geriatric Medicine',
'207QH0002X': 'Allopathic &amp; Osteopathic Physicians/Surgery/Hospice and Palliative Medicine, Family Practice',
'207QS0010X': 'Allopathic &amp; Osteopathic Physicians/Family Medicine, Sports Medicine',
'207QS1201X': 'Allopathic &amp; Osteopathic Physicians/Family Medicine, Sleep Medicine',
'208VP0014X': 'Allopathic &amp; Osteopathic Physicians/Pain Medicine, Interventional Pain Medicine',
'207RG0100X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Gastroenterology',
'207R00000X ': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine',
'207RA0401X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Addiction Medicine',
'207RA0000X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Adolescent Medicine',
'207RA0001X': 'Allopathic &amp; Osteopathic Physicians/Advanced Heart Failure and Transplant Cardiology',
'207RA0201X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Allergy &amp; Immunology',
'207RB0002X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Bariatric Medicine',
'207RI0001X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Clinical &amp; Laboratory Immunology',
'207RC0200X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Critical Care Medicine',
'207RE0101X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Endocrinology, Diabetes &amp; Metabolism',
'207RG0300X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Geriatric Medicine',
'207RH0000X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Hematology',
'207RH0003X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Hematology &amp; Oncology',
'207RI0008X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Hepatology',
'207RH0002X': 'Allopathic &amp; Osteopathic Physicians/Surgery/Hospice and Palliative Medicine, Internal Medicine',
'207RI0200X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Infectious Disease',
'207RM1200X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Magnetic Resonance Imaging (MRI)',
'207RX0202X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Medical Oncology',
'207RN0300X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Nephrology',
'207RP1001X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Pulmonary Disease',
'207RR0500X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Rheumatology',
'207RS0012X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Sleep Medicine',
'207RS0010X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Sports Medicine',
'207RT0003X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Transplant Hepatology',
'204D00000X': 'Allopathic &amp; Osteopathic Physicians/Neuromusculoskeletal Medicine &amp; OMM',
'204C00000X': 'Allopathic &amp; Osteopathic Physicians/Neuromusculoskeletal Medicine, Sports Medicine',
'2084N0400X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Neurology',
'2084N0402X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Neurology with Special Qualifications in Child Neurology',
'2084A2900X': 'Allopathic &amp; Osteopathic Physicians/Psychiatry &amp; Neurology/Neurocritical Care',
'235Z00000X': 'Speech, Language and Hearing Service Providers   ',
'207V00000X ': 'Allopathic &amp; Osteopathic Physicians/Obstetrics &amp; Gynecology',
'207VB0002X': 'Allopathic &amp; Osteopathic Physicians/Obstetrics &amp; Gynecology, Bariatric Medicine',
'207VC0200X': 'Allopathic &amp; Osteopathic Physicians/Obstetrics &amp; Gynecology, Critical Care Medicine',
'207VF0040X': 'Allopathic &amp; Osteopathic Physicians/Obstetrics &amp; Gynecology, Female Pelvic Medicine and Reconstructive Surgery',
'207VX0201X': 'Allopathic &amp; Osteopathic Physicians/Obstetrics &amp; Gynecology, Gynecologic Oncology',
'207VG0400X': 'Allopathic &amp; Osteopathic Physicians/Obstetrics &amp; Gynecology, Gynecology',
'207VH0002X': 'Allopathic &amp; Osteopathic Physicians/Surgery/Hospice and Palliative Medicine, Obstetrics &amp; Gynecology',
'207VM0101X': 'Allopathic &amp; Osteopathic Physicians/Obstetrics &amp; Gynecology, Maternal &amp; Fetal Medicine',
'207VX0000X': 'Allopathic &amp; Osteopathic Physicians/Obstetrics &amp; Gynecology, Obstetrics',
'207VE0102X': 'Allopathic &amp; Osteopathic Physicians/Obstetrics &amp; Gynecology, Reproductive Endocrinology',
'2084H0002X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Hospice &amp; Palliative Medicine',
'207PH0002X': 'Allopathic &amp; Osteopathic Physicians/Emergency Medicine, Hospice and Palliative Medicine',
'207W00000X': 'Allopathic &amp; Osteopathic Physicians/Ophthalmology',
'207WX0009X           ': 'Allopathic &amp; Osteopathic Physicians/Ophthalmology, Glaucoma Specialist',
'207WX0107X    ': 'Allopathic &amp; Osteopathic Physicians/Ophthalmology, Retina Specialist',
'207WX0108X    ': 'Allopathic &amp; Osteopathic Physicians/Ophthalmology, Uveitis and Ocular Inflammatory Disease',
'207WX0109X': 'Allopathic &amp; Osteopathic Physicians/Ophthalmology/Neuro-ophthalmology',
'207WX0110X': 'Allopathic &amp; Osteopathic Physicians/Ophthalmology/Pediatric Ophthalmology and Strabismus Specialist',
'207WX0120X': 'Allopathic &amp; Osteopathic Physicians/Ophthalmology, Cornea and External Diseases Specialist',
'207WX0200X': 'Allopathic &amp; Osteopathic Physicians/Ophthalmic Plastic and Reconstructive Surgery',
'1223S0112X': 'Allopathic &amp; Osteopathic Physicians/Ophthalmology, Dental Providers/Dentist, Oral &amp; Maxillofacial Surgery',
'207X00000X ': 'Allopathic &amp; Osteopathic Physicians/Orthopedic Surgery',
'207RC0001X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Clinical Cardiatric Electrophysiology',
'207ZP0101X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Anatomic Pathology',
'207ZP0102X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Anatomic Pathology &amp; Clinical Pathology',
'207ZB0001X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Blood Banking &amp; Transfusion Medicine',
'207ZP0104X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Chemical Pathology',
'207ZC0006X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Clinical Pathology',
'207ZP0105X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Clinical Pathology/Laboratory Medicine',
'207ZC0500X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Cytopathology',
'207ZD0900X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Dermapathology',
'207ZF0201X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Forensic Pathology',
'207ZH0000X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Hematology',
'207ZI0100X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Immunopathology',
'207ZM0300X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Medical Microbiology',
'207ZP0007X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Molecular Genetic Pathology',
'207ZN0500X': 'Allopathic &amp; Osteopathic Physicians/Pathology, Neuropathology',
'207ZP0213X  ': 'Allopathic &amp; Osteopathic Physicians/Pathology, Pediatric Pathology',
'207PS0010X': 'Allopathic &amp; Osteopathic Physicians/Emergency Medicine, Sports Medicine',
'2080S0010X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Sports Medicine',
'2081P0301X': 'Allopathic &amp; Osteopathic Physicians/Physical Medicine &amp; Rehabilitation, Brain Injury',
'2081S0010X': 'Allopathic &amp; Osteopathic Physicians/Physical Medicine &amp; Rehabilitation, Sports Medicine',
'2083S0010X': 'Allopathic &amp; Osteopathic Physicians/Preventive Medicine, Sports Medicine',
'2084S0010X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Sports Medicine',
'208200000X ': 'Allopathic &amp; Osteopathic Physicians/Plastic Surgery',
'261Q00000X': 'Ambulatory Health Care Facilities/Clinic/Center, Multi-Specialty  ',
'208100000X': 'Allopathic &amp; Osteopathic Physicians/Physical Medicine &amp; Rehabilitation',
'2081H0002X ': 'Allopathic &amp; Osteopathic Physicians/Physical Medicine &amp; Rehabilitation, Hospice and Palliative Medicine',
'2081N0008X': 'Allopathic &amp; Osteopathic Physicians/Physical Medicine &amp; Rehabilitation, Neuromuscular Medicine',
'2081P2900X': 'Allopathic &amp; Osteopathic Physicians/Physical Medicine &amp; Rehabilitation, Pain Medicine',
'2081P0010X': 'Allopathic &amp; Osteopathic Physicians/Physical Medicine &amp; Rehabilitation, Pediatric Rehabilitation Medicine',
'2081P0004X': 'Allopathic &amp; Osteopathic Physicians/Physical Medicine &amp; Rehabilitation, Spinal Cord Injury Medicine',
'2084P0800X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Psychiatry',
'2084P0301X': 'Allopathic &amp; Osteopathic Physicians/Psychiatry &amp; Neurology/Respiratory, Developmental, Rehabilitative and Restorative Service , Brain Injury Medicine',
'2085R0202X': 'Allopathic &amp; Osteopathic Physicians/Radiology, Diagnostic Radiology',
'367H00000X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Anesthesiologist Assistant',
'208800000X ': 'Allopathic &amp; Osteopathic Physicians/Urology',
'2088P0231X': 'Allopathic &amp; Osteopathic Physicians/Urology, Pediatric Urology',
'2088F0040X': 'Female Pelvic Medicine &amp; Reconstructive Surgery',
'111N00000X ': 'Chiropractic Providers/Chiropractor',
'111NI0013X': 'Chiropractic Providers/Chiropractor, Independent Medical Examiner',
'111NI0900X': 'Chiropractic Providers/Chiropractor, Internist',
'111NN0400X': 'Chiropractic Providers/Chiropractor, Neurology',
'111NN1001X': 'Chiropractic Providers/Chiropractor, Nutrition',
'111NX0100X': 'Chiropractic Providers/Chiropractor, Occupational Medicine',
'111NX0800X': 'Chiropractic Providers/Chiropractor, Orthopedic',
'111NP0017X': 'Chiropractic Providers/Chiropractor, Pediatric Chiropractor',
'111NR0200X': 'Chiropractic Providers/Chiropractor, Radiology',
'111NR0400X': 'Chiropractic Providers/Chiropractor, Rehabilitation',
'111NS0005X': 'Chiropractic Providers/Chiropractor, Sports Physician',
'111NT0100X': 'Chiropractic Providers/Chiropractor, Thermography',
'207U00000X ': 'Allopathic &amp; Osteopathic Physicians/Nuclear Medicine',
'207UN0903X': 'Allopathic &amp; Osteopathic Physicians/Nuclear Medicine, In Vivo &amp; In Vitro Nuclear Medicine',
'207UN0901X': 'Allopathic &amp; Osteopathic Physicians/Nuclear Medicine, Nuclear Cardiology',
'207UN0902X': 'Allopathic &amp; Osteopathic Physicians/Nuclear Medicine, Nuclear Imaging &amp; Therapy',
'208000000X ': 'Allopathic &amp; Osteopathic Physicians/Pediatrics',
'2080A0000X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Adolescent Medicine',
'193400000X': 'Group/Single-Specialty',
'2080I0007X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Clinical &amp; Laboratory Immunology',
'2080P0006X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Developmental–Behavioral Pediatrics',
'2080H0002X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Hospice and Palliative Medicine',
'2080T0002X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Medical Toxicology',
'2080N0001X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Neonatal-Perinatal Medicine',
'2080P0008X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Neurodevelopmental Disabilities',
'2080P0201X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Pediatric Allergy &amp; Immunology',
'2080P0202X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Pediatric Cardiology',
'2080P0203X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Pediatric Critical Care Medicine',
'2080P0204X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Pediatric Emergency Medicine',
'2080P0205X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Pediatric Endocrinology',
'2080P0206X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Pediatric Gastroenterology',
'2080P0207X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Pediatric Hematology-Oncology',
'2080P0208X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Pediatric Infectious Diseases',
'2080P0210X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Pediatric Nephrology',
'2080P0214X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Pediatric Pulmonology',
'2080P0216X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Pediatric Rheumatology',
'2080T0004X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Pediatric Transplant Hepatology',
'2080S0012X': 'Allopathic &amp; Osteopathic Physicians/Pediatrics, Sleep Medicine',
'152W00000X': 'Eye and Vision Service Providers/Optometrist',
'152WC0802X': 'Eye and Vision Service Providers/Optometrist, Corneal and Contact Management',
'152WL0500X': 'Eye and Vision Service Providers/Optometrist, Low Vision Rehabilitation',
'152WX0102X': 'Eye and Vision Service Providers/Optometrist, Occupational Vision',
'152WP0200X': 'Eye and Vision Service Providers/Optometrist, Pediatrics',
'152WS0006X': 'Eye and Vision Service Providers/Optometrist, Sports Vision',
'152WV0400X ': 'Eye and Vision Service Providers/Optometrist, Vision Therapy',
'367A00000X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Midwife, Certified Nurse',
'367500000X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Anesthetist, Certified Registered ',
'261QR0208X': 'Ambulatory Health Care Facilities/Clinic-Center, Radiology, Mammography',
'261QR0207X': 'Ambulatory Health Care Facilities/Clinic-Center, Radiology, Mobile Mammography',
'273R00000X': 'Hospital Units/Psychiatric Unit',
'293D00000X': 'Laboratories/Physiological Laboratory',
'213E00000X ': 'Podiatric Medicine &amp; Surgery Service Providers/Podiatrist',
'213ES0103X': 'Podiatric Medicine &amp; Surgery Service Providers/Podiatrist, Foot &amp; Ankle Surgery',
'213ES0131X': 'Podiatric Medicine &amp; Surgery Service Providers/Podiatrist, Foot Surgery',
'213EG0000X': 'Podiatric Medicine &amp; Surgery Service Providers/Podiatrist, General Practice',
'213EP1101X': 'Podiatric Medicine &amp; Surgery Service Providers/Podiatrist, Primary Podiatric Medicine',
'213EP0504X': 'Podiatric Medicine &amp; Surgery Service Providers/Podiatrist, Public Medicine',
'213ER0200X': 'Podiatric Medicine &amp; Surgery Service Providers/Podiatrist, Radiology',
'213ES0000X': 'Podiatric Medicine &amp; Surgery Service Providers/Podiatrist, Sports Medicine',
'261QA1903X': 'Ambulatory Health Care Facilities/Clinic-Center, Ambulatory Surgical',
'363L00000X ': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner',
'363LA2100X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Acute Care',
'363LA2200X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Adult Health',
'363LC1500X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Community Health',
'363LC0200X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Critical Care Medicine',
'363LF0000X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Family',
'363LG0600X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Gerontology',
'363LN0000X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Neonatal',
'363LN0005X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Neonatal, Critical Care',
'363LX0001X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Obstetrics &amp; Gynecology',
'363LX0106X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Occupational Health',
'363LP0200X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Pediatrics',
'363LP0222X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Pediatrics, Critical Care',
'363LP1700X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Perinatal',
'363LP2300X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Primary Care',
'363LP0808X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Psychiatric/Mental Health',
'363LS0200X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, School',
'363LW0102X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Nurse Practitioner, Women’s Health',
'335E00000X': 'Suppliers/Prosthetic/Orthotic Supplier',
'332B00000X ': 'Suppliers/Durable Medical Equipment &amp; Medical Supplies',
'222Z00000X': 'Respiratory, Developmental, Rehabilitative and Restorative Service Providers/Orthotist',
'229N00000X': 'Respiratory, Developmental, Rehabilitative, and Restorative Service Providers/Anaplastologist',
'224P00000X': 'Respiratory, Developmental, Rehabilitative and Restorative Service Providers/Prosthetist',
'333600000X': 'Suppliers/Pharmacy',
'3336C0002X': 'Suppliers/Pharmacy, Clinic Pharmacy',
'3336C0003X': 'Suppliers/Pharmacy, Community/Retail Pharmacy',
'3336C0004X': 'Suppliers/Pharmacy, Compounding Pharmacy',
'3336H0001X': 'Suppliers/Pharmacy, Home Infusion Therapy Pharmacy',
'3336I0012X': 'Suppliers/Pharmacy, Institutional Pharmacy',
'3336L0003X': 'Suppliers/Pharmacy, Long-term Care Pharmacy',
'3336M0002X': 'Suppliers/Pharmacy, Mail Order Pharmacy',
'3336M0003X': 'Suppliers/Pharmacy, Managed Care Organization Pharmacy',
'3336N0007X': 'Suppliers/Pharmacy, Nuclear Pharmacy',
'3336S0011X': 'Suppliers/Pharmacy, Specialty Pharmacy',
'341600000X ': 'Transportation Services/Ambulance',
'3416A0800X': 'Transportation Services/Ambulance, Air Transport',
'3416L0300X': 'Transportation Services/Ambulance, Land Transport',
'3416S0300X': 'Transportation Services/Ambulance, Water Transport',
'251K00000X': 'Agencies/Public Health or Welfare',
'251V00000X': 'Agencies/Voluntary or Charitable',
'103T00000X ': 'Behavioral Health &amp; Social Service Providers/Psychologist',
'103TA0400X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Addiction (Substance Abuse Disorder)',
'103TA0700X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Adult Development &amp; Aging',
'103TC0700X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Clinical',
'103TC2200X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Clinical Child &amp; Adolescent',
'103TB0200X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Cognitive &amp; Behavioral',
'103TC1900X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Counseling',
'103TE1000X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Educational',
'103TE1100X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Exercise &amp; Sports',
'103TF0000X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Family',
'103TF0200X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Forensic',
'103TP2701X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Group Psychotherapy',
'103TH0004X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Health',
'103TH0100X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Health Service',
'103TM1700X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Men &amp; Masculinity',
'103TM1800X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Mental Retardation &amp; Developmental Disabilities',
'103TP0016X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Prescribing (Medical)',
'103TP0814X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Psychoanalysis',
'103TP2700X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Psychotherapy',
'103TR0400X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Rehabilitation',
'103TS0200X': 'Behavioral Health &amp; Social Service Providers/Psychologist, School',
'103TW0100X': 'Behavioral Health &amp; Social Service Providers/Psychologist, Women',
'106E00000X': 'Behavioral Health &amp; Social Service Providers/Assistant Behavior Analyst',
'106S00000X': 'Behavioral Health &amp; Social Service Providers/Technician',
'335V00000X': 'Suppliers/Portable X-Ray Supplier',
'231H00000X': 'Speech, Language and Hearing Service Providers/Audiologist',
'231HA2400X': 'Speech, Language and Hearing Service Providers/Audiologist, Assistive Technology Practitioner',
'225100000X ': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Physical Therapist',
'2251C2600X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Physical Therapist, Cardiopulmonary',
'2251E1300X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Physical Therapist, Electrophysiology, Clinical',
'2251E1200X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Physical Therapist, Ergonomics',
'2251G0304X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Physical Therapist, Geriatrics',
'2251H1200X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Physical Therapist, Hand',
'2251H1300X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Physical Therapist, Human Factors',
'2251N0400X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Physical Therapist, Neurology',
'2251X0800X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Physical Therapist, Orthopedic',
'2251P0200X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Physical Therapist, Pediatrics',
'2251S0007X': 'Respiratory, Rehabilitative &amp; Restorative Service Providers/Physical Therapist, Sports',
'225X00000X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Occupational Therapist',
'225XR0403X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Occupational Therapist, Driving and Community Mobility',
'225XE0001X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Occupational Therapist, Environmental Modification',
'225XE1200X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Occupational Therapist, Ergonomics',
'225XF0002X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Occupational Therapist, Feeding, Eating &amp;Swallowing',
'225XG0600X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Occupational Therapist, Gerontology',
'225XH1200X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Occupational Therapist, Hand',
'225XH1300X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Occupational Therapist, Human Factors',
'225XL0004X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Occupational Therapist, Low Vision',
'225XM0800X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Occupational Therapist, Mental Health',
'225XN1300X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Occupational Therapist, Neurorehabilitation',
'225XP0200X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Occupational Therapist, Pediatrics',
'225XP0019X': 'Respiratory, Developmental, Rehabilitative &amp; Restorative Service Providers/Occupational Therapist, Physical Rehabilitation',
'291U00000X': 'Laboratories/Clinical Medical Laboratory',
'261QM1300X ': 'Ambulatory Health Care Facilities/Clinic/Center, Multi-Specialty  ',
'261QP2000X': 'Ambulatory Health Care Facilities/Clinic/Center, Physical Therapy',
'193200000X': 'Group/Multi-Specialty',
'133V00000X ': 'Dietary &amp; Nutritional Service Providers/Dietician, Registered',
'133VN1006X': 'Dietary &amp; Nutritional Service Providers/Dietician, Registered, Nutrition, Metabolic',
'133VN1004X': 'Dietary &amp; Nutritional Service Providers/Dietician, Registered, Nutrition, Pediatric',
'133VN1005X': 'Dietary &amp; Nutritional Service Providers/Dietician, Registered, Nutrition, Renal',
'208VP0000X': 'Allopathic &amp; Osteopathic Physicians/Pain Medicine, Pain Medicine',
'261QR0200X': 'Ambulatory Health Care Facilities/Clinic/Center, Radiology',
'247200000X': 'Technologists, Technicians &amp; Other Technical Service Providers/Technician, Other',
'207L00000X': 'Allopathic &amp; Osteopathic Physicians/Anesthesiology, Addiction Medicine',
'2084A0401X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology',
'1041C0700X': 'Behavioral Health &amp; Social Service Providers/Social Worker, Clinical',
'2083A0100X': 'Allopathic &amp; Osteopathic Physicians/Preventive Medicine, Aerospace Medicine',
'2083T0002X': 'Allopathic &amp; Osteopathic Physicians/Preventive Medicine, Medical Toxicology',
'2083X0100X': 'Allopathic &amp; Osteopathic Physicians/Preventive Medicine, Occupational Medicine',
'2083P0500X': 'Allopathic &amp; Osteopathic Physicians/Preventive Medicine,  Preventive Medicine/Occupational Environmental Medicine',
'2083P0901X': 'Allopathic &amp; Osteopathic Physicians/Preventive Medicine, Public Health &amp; General Preventive Medicine',
'2083P0011X': 'Allopathic &amp; Osteopathic Physicians/Preventive Medicine, Undersea and Hyperbaric Medicine',
'2084P0802X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Addiction Psychiatry',
'2084B0002X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Bariatric Medicine',
'2084P0804X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Child &amp; Adolescent Psychiatry',
'2084N0600X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Clinical Neurophysiology',
'2084D0003X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Diagnostic Neuroimaging',
'2084F0202X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Forensic Psychiatry',
'2084P0805X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Geriatric Psychiatry',
'2084P0005X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Neurodevelopmental Disabilities',
'2084N0008X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Neuromuscular Medicine',
'2084P2900X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Pain Medicine',
'2084P0015X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Psychosomatic Medicine',
'2084S0012X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Sleep Medicine',
'2084V0102X': 'Allopathic &amp; Osteopathic Physicians/ Psychiatry &amp; Neurology, Vascular Neurology',
'332B00000X': 'Suppliers/Durable Medical Equipment &amp; Medical Supplies',
'364S00000X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist',
'364SA2100X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Acute Care',
'364SA2200X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Adult Health',
'364SC2300X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Chronic Care',
'364SC1501X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Community Health/Public Health',
'364SC0200X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Critical Care Medicine',
'364SE0003X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Emergency',
'364SE1400X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Ethics',
'364SF0001X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Family Health',
'364SG0600X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Gerontology',
'364SH1100X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Holistic',
'364SH0200X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Home Health',
'364SI0800X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Informatics',
'364SL0600X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Long-term Care',
'364SM0705X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Medical-Surgical',
'364SN0000X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Neonatal',
'364SN0800X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Neuroscience',
'364SX0106X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Occupational Health',
'364SX0200X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Oncology',
'364SX0204X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Oncology, Pediatrics',
'364SP0200X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Pediatrics',
'364SP1700X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Perinatal',
'364SP2800X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Perioperative',
'364SP0808X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Psychiatric/Mental Health',
'364SP0809X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Psychiatric/Mental Health, Adult',
'364SP0807X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Psychiatric/Mental Health, Child &amp; Adolescent',
'364SP0810X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Psychiatric/Mental Health, Child &amp; Family',
'364SP0811X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Psychiatric/Mental Health, Chronically Ill',
'364SP0812X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Psychiatric/Mental Health, Community',
'364SP0813X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Psychiatric/Mental Health, Geropsychiatric',
'364SR0400X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Rehabilitation',
'364SS0200X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, School',
'364ST0500X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Transplantation',
'364SW0102X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Clinical Nurse Specialist, Women’s Health',
'2085R0001X': 'Allopathic &amp; Osteopathic Physicians/Radiology, Radiation Oncology',
'207P00000X': 'Allopathic &amp; Osteopathic Physicians/Emergency Medicine',
'207PE0004X': 'Allopathic &amp; Osteopathic Physicians/Emergency Medicine, Emergency Medical Services',
'207PT0002X': 'Allopathic &amp; Osteopathic Physicians/Emergency Medicine, Medical Toxicology',
'207PP0204X': 'Allopathic &amp; Osteopathic Physicians/Emergency Medicine, Pediatric Emergency Medicine',
'207PE0005X': 'Allopathic &amp; Osteopathic Physicians/Emergency Medicine, Undersea and Hyperbaric Medicine',
'2085R0204X': 'Allopathic &amp; Osteopathic Physicians/Radiology, Vascular and Interventional Radiology',
'2085H0002X': 'Hospice &amp; Palliative Medicine',
'156FX1800X': 'Eye &amp; Vision Service Providers/Technician/Technologist, Optician',
'363A00000X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Physician Assistant',
'363AM0700X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Physician Assistant, Medical',
'363AS0400X': 'Physician Assistants &amp; Advanced Practice Nursing Providers/Physician Assistant, Surgical',
'282N00000X': 'Hospitals/General Acute Care Hospital',
'282NC2000X': 'Hospitals/General Acute Care Hospital, Children',
'282E00000X': 'Hospitals/Long Term Care Hospital',
'283Q00000X': 'Hospitals/Psychiatric Hospital',
'283X00000X': 'Hospitals/Rehabilitation Hospital',
'2843000000X': 'Hospitals/Special(ty) Hospital',
'275N00000X': 'Hospital Units/Medicare Defined Swing Bed Unit',
'273Y00000X': 'Hospital Units/Rehabilitation Unit',
'284300000X': 'Hospitals/Special(ty) Hospital',
'282NC0060X': 'Hospitals/General Acute Care Hospital, Critical Access',
'314000000X': 'Nursing and Custodial Care Facilities/Skilled Nursing Facility',
'313M00000X': 'Nursing and Custodial Care Facilities/Nursing Facility',
'251E00000X': 'Agencies/Home Health',
'1835C0205X': 'Suppliers/Pharmacy, Critical Care',
'1835P0200X': 'Suppliers/Pharmacy, Pediatrics',
'332BX2000X': 'Suppliers/Durable Medical Equipment &amp; Medical Supplies, Oxygen Equipment &amp; Supplies',
'261QR0400X': 'Ambulatory Health Care Facilities/Clinic/Center, Rehabilitation',
'335U00000X': 'Suppliers/Organ Procurement Organization',
'261QM0801X': 'Ambulatory Health Care Facilities/Clinic/Center, Mental Health',
'261QR0401X': 'Ambulatory Health Care Facilities/Clinic/Center, Rehabilitation, Comprehensive Outpatient Rehabilitation Facility (CORF)',
'261QE0700X': 'Ambulatory Health Care Facilities/End-Stage Renal Disease (ESRD) Treatment',
'261QF0400X ': 'Ambulatory Health Care Facilities/Federally Qualified Health Center (FQHC)',
'251G00000X': 'Agencies/Hospice Care, Community Based',
'291900000X': 'Laboratories/Military Clinical Medical Laboratory',
'282J00000X': 'Hospitals/Religious Non-medical Health Care Institution',
'261QR1300X': 'Ambulatory Health Care Facilities/Clinic/Center, Rural Health',
'207RI0011X': 'Allopathic &amp; Osteopathic Physicians/Internal Medicine, Interventional Cardiology',
'122300000X ': 'Allopathic &amp; Osteopathic Physicians/Ophthalmology, Dental Providers/Dentist',
'208M00000X ': 'Allopathic &amp; Osteopathic Physicians/Hospitalist',
'207RA0001X ': 'Allopathic &amp; Osteopathic Physicians/Advanced Heart Failure and Transplant Cardiology'
}






